name: dbt_migration

profile: snowflake_demo

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbt_migration:
    +schema: informatica_source
    u0287d01:
      +column_types:
        SSN: varchar(9)
        NAME: varchar(30)
        CURRENT_ACCT: varchar(6)
        CURRENT_ORG: varchar(7)
        FLSA_STATUS: varchar(1)
        COMP_TIME_CUR_BAL: number(8,2)
        COMP_TIME_YEAR_EARNED: number(4,0)
        PP_END_DATE: varchar(8)
        DAILY_DATE_EARNED: varchar(8)
        COMP_TIME_RATE: number(6,2)
        COMP_TIME_HOURS: number(8,2)
        COMP_TIME_UNDEF: number(6,0)
    pay_period:
      +column_types:
        pp_num: number(2,0)
        pp_end_year: number(4,0)
        pp_start_dte: date
        pp_end_dte: date
        lv_num: number(2,0)
        lv_year: number(4,0)
        pay_dte: date
        curr_pp_flag: varchar(1)
        holiday_1: date
        holiday_2: date
    comp_time_daily_tbl:
      +schema: informatica_gold
      +column_types:
        PP_END_YEAR: number(4,0)
        PP_NUM: number(2,0)
        PP_YEAR_NUM: number(6,0)
        SSN: varchar(9)
        NAME: varchar(30)
        CURRENT_ACCT: varchar(6)
        CURRENT_ORG: varchar(7)
        FLSA_STATUS: varchar(1)
        COMP_TIME_CUR_BAL: number(8,2)
        COMP_TIME_YEAR_EARNED: number(4,0)
        PP_END_DATE: date
        DAILY_DATE_EARNED: date
        COMP_TIME_RATE: number(6,2)
        COMP_TIME_HOURS: number(8,2)
        COMP_TIME_UNDEF: number(6,0)
    pseudossn_file:
      +schema: informatica_pseudossn
      +column_types:
        SSN: varchar(9)
        CAN_CD: varchar(8)
        PSEUDO_SSN: varchar(9)
        EIN: varchar(8)
        EMP_REC_NO: varchar(2)
        LEGACY_APPT_NO: varchar(2)
        FIRST_NAME: varchar(11)
        MIDDLE_INIT: varchar(1)
        LAST_NAME: varchar(16)
        SEX: varchar(1)
        VET_PREF: varchar(1)
        TENURE_CD: varchar(1)
        POSITION_CD: varchar(1)
        CITIZENSHIP_STATUS: varchar(1)
        APPT_TYPE_CD: varchar(2)
        HIRE_DATE: varchar(8)
        HANDICAP_CODE: varchar(2)
        UNIF_ALLOW_CODE: varchar(3)
        UNIF_ALLOW_DATE: varchar(8)
        UNIF_ALLOW_AMT: varchar(6)
        RSSSDP: varchar(4)
        CEILING_CODE: varchar(1)
        FUNCTION_CODE: varchar(1)
        EMPLOYEE_STATUS: varchar(1)
        MANAGER_STATUS: varchar(1)
        POSITION_SENS_CODE: varchar(1)
        CAREER_START_DATE: varchar(8)
        CAREER_CONV_DATE: varchar(8)
        PROBATION_DATE: varchar(8)
        ABNORMAL_RATE_CODE: varchar(1)
        APPT_LIMIT_HRS: varchar(7)
        APPT_LIMIT_PAY: varchar(8)
        LAST_PAY_CHANGE: varchar(8)
        CHARITY_AREA_CODE: varchar(3)
        CHARITY_EFF_DATE: varchar(8)
        CHARITY_DED_AMT: varchar(6)
        LAST_NOA: varchar(4)
        FILLER_1: varchar(4)
        QUARTERS_DEDUCTION: varchar(8)
        SUBSIST_DEDUCTION: varchar(8)
        PAY_BASIS: varchar(2)
        WORK_SCHEDULE: varchar(1)
        OCCUPATION_CODE: varchar(4)
        FILLER_2: varchar(3)
        GEO_LOCATION: varchar(9)
        JOB_INDICATOR: varchar(1)
        REG_TEMP: varchar(1)
        SEPARATION_DATE: varchar(8)
        FILLER_3: varchar(1)
        PCA_CONTR_EFF_START_DATE: varchar(8)
        PCA_CONTR_EFF_END_DATE: varchar(8)
        MAX_ANNUAL_PAY: varchar(8)
        PCA_BIWEEKLY_AMOUNT: varchar(8)
        FILLER_4: varchar(33)
        PAY_PLAN_CD: varchar(2)
        APP_LIMIT_DATE: varchar(8)
        SPO_CD: varchar(4)
        TERM_ID: varchar(2)
        EFFECTIVE_DATE: varchar(8)
        EFFECTIVE_SEQ: varchar(3)
        FILLER_5: varchar(9)
        PAY_TABL_NO: varchar(4)
        BUSINESS_UNIT: varchar(5)
        DEPTID: varchar(10)
        PCA_CONTR_YEAR: varchar(2)
        FILLER_6: varchar(150)
    pseudossn_file_tk_num:
      +schema: informatica_pseudossn
      +column_types:
        SSN: varchar(9)
        CAN_CD: varchar(8)
        PSEUDO_SSN: varchar(9)
        EIN: varchar(8)
        EMP_REC_NO: varchar(2)
        LEGACY_APPT_NO: varchar(2)
        FIRST_NAME: varchar(11)
        MIDDLE_INIT: varchar(1)
        LAST_NAME: varchar(16)
        SEX: varchar(1)
        VET_PREF: varchar(1)
        TENURE_CD: varchar(1)
        POSITION_CD: varchar(1)
        CITIZENSHIP_STATUS: varchar(1)
        APPT_TYPE_CD: varchar(2)
        HIRE_DATE: varchar(8)
        HANDICAP_CODE: varchar(2)
        UNIF_ALLOW_CODE: varchar(3)
        UNIF_ALLOW_DATE: varchar(8)
        UNIF_ALLOW_AMT: varchar(6)
        RSSSDP: varchar(4)
        CEILING_CODE: varchar(1)
        FUNCTION_CODE: varchar(1)
        EMPLOYEE_STATUS: varchar(1)
        MANAGER_STATUS: varchar(1)
        POSITION_SENS_CODE: varchar(1)
        CAREER_START_DATE: varchar(8)
        CAREER_CONV_DATE: varchar(8)
        PROBATION_DATE: varchar(8)
        ABNORMAL_RATE_CODE: varchar(1)
        APPT_LIMIT_HRS: varchar(7)
        APPT_LIMIT_PAY: varchar(8)
        LAST_PAY_CHANGE: varchar(8)
        CHARITY_AREA_CODE: varchar(3)
        CHARITY_EFF_DATE: varchar(8)
        CHARITY_DED_AMT: varchar(6)
        LAST_NOA: varchar(4)
        FILLER_1: varchar(4)
        QUARTERS_DEDUCTION: varchar(8)
        SUBSIST_DEDUCTION: varchar(8)
        PAY_BASIS: varchar(2)
        WORK_SCHEDULE: varchar(1)
        OCCUPATION_CODE: varchar(4)
        FILLER_2: varchar(3)
        GEO_LOCATION: varchar(9)
        JOB_INDICATOR: varchar(1)
        REG_TEMP: varchar(1)
        SEPARATION_DATE: varchar(8)
        FILLER_3: varchar(1)
        PCA_CONTR_EFF_START_DATE: varchar(8)
        PCA_CONTR_EFF_END_DATE: varchar(8)
        MAX_ANNUAL_PAY: varchar(8)
        PCA_BIWEEKLY_AMOUNT: varchar(8)
        FILLER_4: varchar(33)
        PAY_PLAN_CD: varchar(2)
        APP_LIMIT_DATE: varchar(8)
        SPO_CD: varchar(4)
        TERM_ID: varchar(2)
        EFFECTIVE_DATE: varchar(8)
        EFFECTIVE_SEQ: varchar(3)
        FILLER_5: varchar(9)
        PAY_TABL_NO: varchar(4)
        BUSINESS_UNIT: varchar(5)
        DEPTID: varchar(10)
        PCA_CONTR_YEAR: varchar(2)
        FILLER_6: varchar(150)
        TK_NUM: varchar(5)
    hi_arch_pseudossn_tbl:
      +schema: informatica_pseudossn
      +column_types:
        SSN: varchar(9)
        CAN_CD: varchar(8)
        PSEUDOSSN: varchar(9)
        EMPLID: varchar(8)
        EMPL_RCD: varchar(2)
        APPT_NUM: varchar(2)
        EMP_FIRST_NAME: varchar(11)
        EMP_MID_INIT: varchar(1)
        EMP_LAST_NAME: varchar(16)
        SEX: varchar(1)
        VETERANS_PREFERENCE_CD: varchar(1)
        TENURE_CD: varchar(1)
        POSITION_NUM: varchar(1)
        US_CITIZENSHIP_CD: varchar(1)
        APPT_TYPE_CD: varchar(2)
        HIRE_DATE: date
        HANDICAP_CD: varchar(2)
        UNF_ALLOW_CD: varchar(3)
        UNIF_ALLOW_DATE: date
        UNIF_ALLOW_AMT: number(10,2)
        RSSSDP: varchar(3)
        CEIL_REPORTING_CD: varchar(1)
        FUNCTNL_CLASSFCTN_CD: varchar(1)
        EMP_STATUS: varchar(1)
        MANAGER_STATUS: varchar(1)
        POSITION_SENSITIVITY_CD: varchar(1)
        CAREER_START_DATE: date
        CAREER_CONV_DATE: date
        PROBATION_DATE: date
        ABNORMAL_RATE_CD: varchar(1)
        APPT_LIMIT_HRS: number(10,2)
        APPT_LIMIT_PAY: number(10,2)
        LAST_PAY_CHANGE: date
        CHARITY_AREA_CD: varchar(3)
        CHARITY_EFF_DATE: date
        CHARITY_DED_AMT: number(10,2)
        LAST_NOA_CD: varchar(4)
        QUARTERS_DED_AMT: number(10,2)
        SUBSIST_DED_AMT: number(10,2)
        PAY_BASIS_CD: varchar(2)
        WORK_SCHEDULE_CD: varchar(1)
        OCCUPATION_CD: varchar(4)
        DUTY_STATION: varchar(9)
        JOB_IND: varchar(1)
        REG_TEMP_CD: varchar(1)
        SEPERATION_DATE: date
        PCA_CONTR_EFF_START_DATE: date
        PCA_CONTR_EFF_END_DATE: date
        MAX_ANNUAL_PAY: number(10,2)
        PCA_BIWEEKLY_AMT: number(10,2)
        PAY_PLAN_CD: varchar(2)
        APPT_NTE_DTE: date
        SPECIAL_PROGRAM_CD: varchar(4)
        TERM_ID: varchar(2)
        EFFECTIVE_DATE: date
        EFFECTIVE_SEQ: number(5,0)
        PAY_TABL_NO: varchar(4)
        BUSINESS_UNIT: varchar(5)
        DEPTID: varchar(10)
        PCA_CONTR_LEN_YEAR: number(4,0)
        TK_NUM: varchar(5)
        PP_NUM: number(2,0)
        PP_END_YEAR: number(4,0)

    pseudossn_file_fivetran:
      +schema: fivetran_pseudossn
      +column_types:
        SSN: varchar(9)
        CAN_CD: varchar(8)
        PSEUDO_SSN: varchar(9)
        EIN: varchar(8)
        EMP_REC_NO: varchar(2)
        LEGACY_APPT_NO: varchar(2)
        FIRST_NAME: varchar(11)
        MIDDLE_INIT: varchar(1)
        LAST_NAME: varchar(16)
        SEX: varchar(1)
        VET_PREF: varchar(1)
        TENURE_CD: varchar(1)
        POSITION_CD: varchar(1)
        CITIZENSHIP_STATUS: varchar(1)
        APPT_TYPE_CD: varchar(2)
        HIRE_DATE: varchar(8)
        HANDICAP_CODE: varchar(2)
        UNIF_ALLOW_CODE: varchar(3)
        UNIF_ALLOW_DATE: varchar(8)
        UNIF_ALLOW_AMT: varchar(6)
        RSSSDP: varchar(4)
        CEILING_CODE: varchar(1)
        FUNCTION_CODE: varchar(1)
        EMPLOYEE_STATUS: varchar(1)
        MANAGER_STATUS: varchar(1)
        POSITION_SENS_CODE: varchar(1)
        CAREER_START_DATE: varchar(8)
        CAREER_CONV_DATE: varchar(8)
        PROBATION_DATE: varchar(8)
        ABNORMAL_RATE_CODE: varchar(1)
        APPT_LIMIT_HRS: varchar(7)
        APPT_LIMIT_PAY: varchar(8)
        LAST_PAY_CHANGE: varchar(8)
        CHARITY_AREA_CODE: varchar(3)
        CHARITY_EFF_DATE: varchar(8)
        CHARITY_DED_AMT: varchar(6)
        LAST_NOA: varchar(4)
        FILLER_1: varchar(4)
        QUARTERS_DEDUCTION: varchar(8)
        SUBSIST_DEDUCTION: varchar(8)
        PAY_BASIS: varchar(2)
        WORK_SCHEDULE: varchar(1)
        OCCUPATION_CODE: varchar(4)
        FILLER_2: varchar(3)
        GEO_LOCATION: varchar(9)
        JOB_INDICATOR: varchar(1)
        REG_TEMP: varchar(1)
        SEPARATION_DATE: varchar(8)
        FILLER_3: varchar(1)
        PCA_CONTR_EFF_START_DATE: varchar(8)
        PCA_CONTR_EFF_END_DATE: varchar(8)
        MAX_ANNUAL_PAY: varchar(8)
        PCA_BIWEEKLY_AMOUNT: varchar(8)
        FILLER_4: varchar(33)
        PAY_PLAN_CD: varchar(2)
        APP_LIMIT_DATE: varchar(8)
        SPO_CD: varchar(4)
        TERM_ID: varchar(2)
        EFFECTIVE_DATE: varchar(8)
        EFFECTIVE_SEQ: varchar(3)
        FILLER_5: varchar(9)
        PAY_TABL_NO: varchar(4)
        BUSINESS_UNIT: varchar(5)
        DEPTID: varchar(10)
        PCA_CONTR_YEAR: varchar(2)
        FILLER_6: varchar(150)
    pseudossn_file_tk_num_fivetran:
      +schema: fivetran_pseudossn
      +column_types:
        SSN: varchar(9)
        CAN_CD: varchar(8)
        PSEUDO_SSN: varchar(9)
        EIN: varchar(8)
        EMP_REC_NO: varchar(2)
        LEGACY_APPT_NO: varchar(2)
        FIRST_NAME: varchar(11)
        MIDDLE_INIT: varchar(1)
        LAST_NAME: varchar(16)
        SEX: varchar(1)
        VET_PREF: varchar(1)
        TENURE_CD: varchar(1)
        POSITION_CD: varchar(1)
        CITIZENSHIP_STATUS: varchar(1)
        APPT_TYPE_CD: varchar(2)
        HIRE_DATE: varchar(8)
        HANDICAP_CODE: varchar(2)
        UNIF_ALLOW_CODE: varchar(3)
        UNIF_ALLOW_DATE: varchar(8)
        UNIF_ALLOW_AMT: varchar(6)
        RSSSDP: varchar(4)
        CEILING_CODE: varchar(1)
        FUNCTION_CODE: varchar(1)
        EMPLOYEE_STATUS: varchar(1)
        MANAGER_STATUS: varchar(1)
        POSITION_SENS_CODE: varchar(1)
        CAREER_START_DATE: varchar(8)
        CAREER_CONV_DATE: varchar(8)
        PROBATION_DATE: varchar(8)
        ABNORMAL_RATE_CODE: varchar(1)
        APPT_LIMIT_HRS: varchar(7)
        APPT_LIMIT_PAY: varchar(8)
        LAST_PAY_CHANGE: varchar(8)
        CHARITY_AREA_CODE: varchar(3)
        CHARITY_EFF_DATE: varchar(8)
        CHARITY_DED_AMT: varchar(6)
        LAST_NOA: varchar(4)
        FILLER_1: varchar(4)
        QUARTERS_DEDUCTION: varchar(8)
        SUBSIST_DEDUCTION: varchar(8)
        PAY_BASIS: varchar(2)
        WORK_SCHEDULE: varchar(1)
        OCCUPATION_CODE: varchar(4)
        FILLER_2: varchar(3)
        GEO_LOCATION: varchar(9)
        JOB_INDICATOR: varchar(1)
        REG_TEMP: varchar(1)
        SEPARATION_DATE: varchar(8)
        FILLER_3: varchar(1)
        PCA_CONTR_EFF_START_DATE: varchar(8)
        PCA_CONTR_EFF_END_DATE: varchar(8)
        MAX_ANNUAL_PAY: varchar(8)
        PCA_BIWEEKLY_AMOUNT: varchar(8)
        FILLER_4: varchar(33)
        PAY_PLAN_CD: varchar(2)
        APP_LIMIT_DATE: varchar(8)
        SPO_CD: varchar(4)
        TERM_ID: varchar(2)
        EFFECTIVE_DATE: varchar(8)
        EFFECTIVE_SEQ: varchar(3)
        FILLER_5: varchar(9)
        PAY_TABL_NO: varchar(4)
        BUSINESS_UNIT: varchar(5)
        DEPTID: varchar(10)
        PCA_CONTR_YEAR: varchar(2)
        FILLER_6: varchar(150)
        TK_NUM: varchar(5)
    hi_arch_pseudossn_tbl_fivetran:
      +schema: fivetran_pseudossn
      +column_types:
        SSN: varchar(9)
        CAN_CD: varchar(8)
        PSEUDOSSN: varchar(9)
        EMPLID: varchar(8)
        EMPL_RCD: varchar(2)
        APPT_NUM: varchar(2)
        EMP_FIRST_NAME: varchar(11)
        EMP_MID_INIT: varchar(1)
        EMP_LAST_NAME: varchar(16)
        SEX: varchar(1)
        VETERANS_PREFERENCE_CD: varchar(1)
        TENURE_CD: varchar(1)
        POSITION_NUM: varchar(1)
        US_CITIZENSHIP_CD: varchar(1)
        APPT_TYPE_CD: varchar(2)
        HIRE_DATE: date
        HANDICAP_CD: varchar(2)
        UNF_ALLOW_CD: varchar(3)
        UNIF_ALLOW_DATE: date
        UNIF_ALLOW_AMT: number(10,2)
        RSSSDP: varchar(3)
        CEIL_REPORTING_CD: varchar(1)
        FUNCTNL_CLASSFCTN_CD: varchar(1)
        EMP_STATUS: varchar(1)
        MANAGER_STATUS: varchar(1)
        POSITION_SENSITIVITY_CD: varchar(1)
        CAREER_START_DATE: date
        CAREER_CONV_DATE: date
        PROBATION_DATE: date
        ABNORMAL_RATE_CD: varchar(1)
        APPT_LIMIT_HRS: number(10,2)
        APPT_LIMIT_PAY: number(10,2)
        LAST_PAY_CHANGE: date
        CHARITY_AREA_CD: varchar(3)
        CHARITY_EFF_DATE: date
        CHARITY_DED_AMT: number(10,2)
        LAST_NOA_CD: varchar(4)
        QUARTERS_DED_AMT: number(10,2)
        SUBSIST_DED_AMT: number(10,2)
        PAY_BASIS_CD: varchar(2)
        WORK_SCHEDULE_CD: varchar(1)
        OCCUPATION_CD: varchar(4)
        DUTY_STATION: varchar(9)
        JOB_IND: varchar(1)
        REG_TEMP_CD: varchar(1)
        SEPERATION_DATE: date
        PCA_CONTR_EFF_START_DATE: date
        PCA_CONTR_EFF_END_DATE: date
        MAX_ANNUAL_PAY: number(10,2)
        PCA_BIWEEKLY_AMT: number(10,2)
        PAY_PLAN_CD: varchar(2)
        APPT_NTE_DTE: date
        SPECIAL_PROGRAM_CD: varchar(4)
        TERM_ID: varchar(2)
        EFFECTIVE_DATE: date
        EFFECTIVE_SEQ: number(5,0)
        PAY_TABL_NO: varchar(4)
        BUSINESS_UNIT: varchar(5)
        DEPTID: varchar(10)
        PCA_CONTR_LEN_YEAR: number(4,0)
        TK_NUM: varchar(5)
        PP_NUM: number(2,0)
        PP_END_YEAR: number(4,0)
models:
  dbt_migration:
    +static_analysis: strict
