name: dbt_migration

profile: snowflake_demo

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_migration:
    +static_analysis: strict
